### ISSUE TITLE
Need keyboard shortcuts for debug step over & step out

### ISSUE THREAD

**Issue by DaleSchultz** [TheGameCreators/AGKIDE#13]
This is a feature request for keyboard shortcuts.

When debugging and stepping through code we often need to step over a function call. At present in the AGKIDE we have to open the debug menu to do so, which breaks the flow of repeatedly stepping over functions.

Similar shortcuts were added to studio, F11 being for step over. Note however that F11 toggles full screen mode so Ctrl+F10 or Shift+f10 may make more sense.

**Comment by adambiser** [comment]
You can assign your own shortcuts in Edit -> Preferences -> Keybindings
Near the bottom, there's a section called "Debug".
You can change Step Over and Step Out to F11 and F12 if you want.
I don't use full screen, so I overwrote the F11 binding so that it's only for Step Over.

**Comment by DaleSchultz** [comment]
ah many thanks Adam...

**Comment by DaleSchultz** [comment]
can redefine keys ourselves.
